### ISSUE TITLE
Responsive

### ISSUE THREAD

**Issue by Alirezamxz** [homfarnam/farnamh.ir#1]
اسم هدر در سایز موبایل بزرگ است و باعث اسکرول افقی میشود
![Screenshot_20200723-203913_Chrome](https://user-images.githubusercontent.com/47672255/88310401-e0aa5f00-cd24-11ea-91db-50a0418ac279.jpg)

**Comment by homfarnam** [comment]
Please Check Again

**Comment by Alirezamxz** [comment]
Not fixed yet
![Annotation 2020-07-24 103840](https://user-images.githubusercontent.com/47672255/88365086-2ce3b680-cd9a-11ea-9e45-69a0a2a1ba29.png)

**Comment by homfarnam** [comment]
I think now it works well.
Please check again.

**Comment by Alirezamxz** [comment]
Fixed 👍
